# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: sling

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/slingdata-io/sling' go.mod
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/sling
    
    env:
      - CGO_ENABLED=1
    
    tags:
      - fts5

    goarch:
      - arm64
    
    goos:
      - linux
    ldflags:
      - "-X 'github.com/slingdata-io/sling-cli/core.Version={{.Version}}' -X 'github.com/slingdata-io/sling-cli/core/env.PlausibleURL={{.Env.PLAUSIBLE_URL}}' -X 'github.com/slingdata-io/sling-cli/core/env.SentryDsn={{.Env.SENTRY_DSN}}'"

snapshot:
  name_template: "{{ incpatch .Version }}"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

checksum:
  name_template: '{{ .Runtime.Goos }}.{{ .Runtime.Goarch }}.checksums.txt'

# Could figure out how to make arm64 work, pushing manually
# dockers:
#   - dockerfile: 'cmd/sling/Dockerfile.arm64'
#     image_templates:
#     - "slingdata/sling:{{ .Tag }}-arm64"

release:
  mode: replace
  header: |
    ## Sling {{ .Tag }} ({{ .Date }})