name: Test Build

on: [workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACE_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACE_SECRET_KEY}}
  PLAUSIBLE_URL: ${{ secrets.PLAUSIBLE_URL }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  GOPRIVATE: github.com/slingdata-io/*
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  # test1:
  #   runs-on: [self-hosted, Linux, ARM64]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
      
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: "1.22"
  #         cache: true
          
  #     - name: Build Sling
  #       run: bash scripts/build.sh

  #     - name: Build Docker
  #       run: |
  #         docker build -f cmd/sling/Dockerfile.arm64 -t slingdata/sling:dev-arm64 . 

  build-brew:
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 20
    # runs-on: macos-latest

    defaults:
      run:
        working-directory: /tmp

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"
          cache: false
        
      - name: Configure private token
        run: |
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.mac.yaml

  build-scoop:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"
          cache: true

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"
        
      - name: Configure private token
        run: |
          $url = ("https://" + $env:GITHUB_TOKEN + ":x-oauth-basic@github.com/")
          git config --global url."$url".insteadOf "https://github.com/"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.windows.yaml

  build-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"
          cache: false

      - name: Login docker
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u slingdata --password-stdin
        
      - name: Configure private token
        run: |
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.linux.arm64.yaml

  build-linux-amd64:
    # runs-on: ubuntu-20.04
    runs-on: [self-hosted, Linux, X64, ubuntu-16]
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"
          cache: false

      - name: Login docker
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u slingdata --password-stdin
        
      - name: Configure private token
        run: |
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: build --clean --skip=validate -f .goreleaser.linux.amd64.yaml